tiff(filename = "inkvsAge.tiff")
plot(degree(graSta, mode = "in")[datNod$kcd], datNod$meanAge, xlab = "in degree", ylab = "mean age")
dev.off()
tiff(filename = "inkvsAgeLogX.tiff")
plot(degree(graSta, mode = "in")[datNod$kcd], datNod$meanAge, xlab = "in degree", ylab = "mean age", log = "x")
dev.off()
tiff(filename = "outkvsAge.tiff")
plot(degree(graSta, mode = "out")[datNod$kcd], datNod$meanAge, xlab = "out degree", ylab = "mean age")
dev.off()
tiff(filename = "outkvsAgeLogX.tiff")
plot(degree(graSta, mode = "out")[datNod$kcd], datNod$meanAge, xlab = "out degree", ylab = "mean age", log = "x")
dev.off()
tiff(filename = "CvsAge.tiff")
plot(transitivity(graSta, type = "local")[match(datNod$kcd, V(graSta)$name)], datNod$meanAge, xlab = "clustering coefficient (transitivity)", ylab = "mean age")
dev.off()
datNod$transi <- transitivity(graSta, type = "local")[match(datNod$kcd, V(graSta)$name)]
names(datNod$transi) <- datNod$kcd
datNod$transi[match(V(graSta)$name, datNod$kcd)] <- transitivity(graSta, type = "local")

datNod$outk <- degree(graSta, mode = "out")[as.character(datNod$kcd)]
datNod$outs <- strength(graCom, mode = "out")[as.character(datNod$kcd)]
datNod$ins <- strength(graCom, mode = "in")[as.character(datNod$kcd)]
datNod$ink <- degree(graSta, mode = "in")[as.character(datNod$kcd)]
kcdClaLab <- scan("kcd-labels.txt", what = "", sep = "\n")
datNodFac <- factor(substr(datNod$kcd, 1, 1))
levels(datNodFac) <- kcdClaLab
tiff(filename = "classvsoutk.tiff")
par(mar = par()$mar + c(0, 15, 0, 0))
plot(datNodFac, datNod$outk, legend.text = kcdClaLab, las = 1, horizontal = TRUE, xlab = "out degree")
dev.off()
tiff(filename = "classvsoutk.tiff")
par(mar = par()$mar + c(0, 15, 0, 0))
plot(datNodFac, datNod$outk, legend.text = kcdClaLab, las = 1, horizontal = TRUE, xlab = "out degree")
dev.off()
tiff(filename = "classvsink.tiff")
par(mar = par()$mar + c(0, 15, 0, 0))
plot(datNodFac, datNod$ink, legend.text = kcdClaLab, las = 1, horizontal = TRUE, xlab = "out degree")
plot(datNodFac, datNod$ink, legend.text = kcdClaLab, las = 1, horizontal = TRUE, xlab = "in degree")
dev.off()
tiff(filename = "classvsouts.tiff")
par(mar = par()$mar + c(0, 15, 0, 0))
plot(datNodFac, datNod$outs, legend.text = kcdClaLab, las = 1, horizontal = TRUE, xlab = "out strength")
dev.off()
tiff(filename = "classvsins.tiff")
par(mar = par()$mar + c(0, 15, 0, 0))
plot(datNodFac, datNod$ins, legend.text = kcdClaLab, las = 1, horizontal = TRUE, xlab = "in strength")
dev.off()
tiff(filename = "classvsc.tiff")
par(mar = par()$mar + c(0, 15, 0, 0))
plot(datNodFac, datNod$transi, legend.text = kcdClaLab, las = 1, horizontal = TRUE, xlab = "clustering coefficient (transitivity)")
dev.off()
tiff(filename = "outkvsNumAll.tiff")
plot(datNod$outk, datNod$number, log = "xy", xlab = "out degree", ylab = "number of patients", pch = 21, cex = 2, bg = "gray", col = "gray")
points(datNod$outk, datNod$sex1, col = "blue", pch = 2)
points(datNod$outk, datNod$sex2, col = "red")
dev.off()
tiff(filename = "outkvsNumTot.tiff")
plot(datNod$outk, datNod$number, log = "xy", xlab = "out degree", ylab = "number of patients")
dev.off()
tiff(filename = "outkvsNumMF.tiff")
plot(datNod$outk, datNod$sex2, log = "xy", xlab = "out degree", ylab = "number of patients", pch = 21, cex = 2, bg = "pink")
points(datNod$outk, datNod$sex1, col = "blue")
dev.off()
tiff(filename = "inkvsNumTot.tiff")
plot(datNod$ink, datNod$number, log = "xy", xlab = "in degree", ylab = "number of patients", pch = 21, cex = 2, bg = "gray", col = "gray")
points(datNod$ink, datNod$sex1, pch = 2, col = "blue")
points(datNod$ink, datNod$sex2, col = "red")
dev.off()
tiff(filename = "outsvsNumTot.tiff")
plot(datNod$outs, datNod$number, log = "xy", xlab = "out strength", ylab = "number of patients", pch = 21, cex = 2, bg = "gray", col = "gray")
points(datNod$outs, datNod$sex1, pch = 2, col = "blue")
points(datNod$outs, datNod$sex2, col = "red")
dev.off()
tiff(filename = "insvsNum.tiff")
plot(datNod$ins, datNod$number, log = "xy", xlab = "in strength", ylab = "number of patients", pch = 21, cex = 2, bg = "gray", col = "gray")
points(datNod$ins, datNod$sex1, pch = 2, col = "blue")
points(datNod$ins, datNod$sex2, col = "red")
dev.off()
tiff(filename = "cvsNum.tiff")
plot(datNod$transi, datNod$number, log = "xy", xlab = "clustering ocoefficient (transitivity)", ylab = "number of patients", pch = 21, cex = 2, bg = "gray", col = "gray")
points(datNod$transi, datNod$sex1, pch = 2, col = "blue")
points(datNod$transi, datNod$sex2, col = "red")
dev.off()
datNodColFac <- datNodFac
levels(datNodColFac) <- rainbow(19)
tiff(filename = "ink-vs-outk-class")
plot(datNod$outk, datNod$ink, xlab = "out degree", ylab = "in degree", log = "xy", pch = 21, cex = (datNod$number * 64)/max(datNod$number) + 1, bg = as.character(datNodColFac))
dev.off()
tiff(filename = "ink-vs-outk-agecol")
plot(datNod$outk, datNod$ink, xlab = "out degree", ylab = "in degree", log = "xy", pch = 21, cex = (datNod$number * 64)/max(datNod$number) + 1, bg = as.character(datNod$ageColor))
dev.off()
tiff(filename = "ink-vs-outk-sexcol")
plot(datNod$outk, datNod$ink, xlab = "out degree", ylab = "in degree", log = "xy", pch = 21, cex = (datNod$number * 64)/max(datNod$number) + 1, bg = as.character(datNod$sexColor))
dev.off()
tiff(filename = "ins-vs-outs-class.tiff")
plot(datNod$outs, datNod$ins, xlab = "out strength", ylab = "in strength", pch = 21, bg = as.character(datNodColFac))
dev.off()
tiff(filename = "ins-vs-outs-ageColor.tiff")
plot(datNod$outs, datNod$ins, xlab = "out strength", ylab = "in strength", pch = 21, bg = as.character(datNod$ageColor))
dev.off()
tiff(filename = "ins-vs-outs-sexColor.tiff")
plot(datNod$outs, datNod$ins, xlab = "out strength", ylab = "in strength", pch = 21, bg = as.character(datNod$sexColor))
dev.off()
datNodSor <- datNod[sort(datNod$number, decreasing = TRUE, index.return = TRUE)$ix,]
tiff(filename = "ins-vs-outs-AgeCNumSz.tiff")
plot(datNodSor$outs, datNod$ins, xlab = "out strength", ylab = "in strength", pch = 21, cex = (datNod$number * 32)/max(datNod$number) + 1, bg = as.character(datNod$ageColor))
dev.off()
lmCom <- lm(ins ~ outs, datNod)
tiff(filename = "outs-vs-ins-regres.tiff")
plot(datNod$outs, datNod$ins, xlab = "out strength", ylab = "in strength", pch = 21, bg = as.character(datNod$ageColor))
lines(c(min(datNod$outs), max(datNod$outs)), predict(lmCom, data.frame(outs = c(min(datNod$outs), max(datNod$outs)))))
legend("bottomright", "in strength \n ~ 0.65 x out strength + 245.7")
dev.off()
datNod[head(sort(datNod$outs + 0.65 * datNod$ins, decreasing = TRUE, index.return = TRUE)$ix),]
979.9598 + 976.4322 * 0.65
lines(c(0, 1614.641), c(1614.641/0.65, 0), lty = 2)
datNod[head(sort(datNod$outs + 0.65 * datNod$ins, index.return = TRUE)$ix),]
416.7876 + 0.65 * 544.2082
lines(c(0, 770.7876), c(770.7876 / 0.65, 0), lty = 2)
datNod[head(sort(datNod$ins - datNod$outs * 0.65, decreasing = TRUE, index.return = TRUE)$ix),]
1048.798 - 578.8011 * 0.65
lines(c(0,900), c(672.5773, 900 * 0.65 + 672.5773), lty = 2)
datNod[head(sort(datNod$ins - datNod$outs * 0.65, index.return = TRUE)$ix),]
521.3711 - 0.65 * 724.6448
lines(c(0, 1100), c(50.35198, 1100 * 0.65 + 50.35198), lty = 2)
tiff(filename = "outs-vs-ins-exampl.tiff")
plot(datNod$outs, datNod$ins, xlab = "out strength", ylab = "in strength", pch = 21, bg = as.character(datNod$ageColor))
lines(c(min(datNod$outs), max(datNod$outs)), predict(lmCom, data.frame(outs = c(min(datNod$outs), max(datNod$outs)))))
legend("bottomright", "in strength \n ~ 0.65 x out strength + 245.7")
lines(c(0, 1614.641), c(1614.641/0.65, 0), lty = 2)
lines(c(0, 770.7876), c(770.7876 / 0.65, 0), lty = 2)
lines(c(0,900), c(672.5773, 900 * 0.65 + 672.5773), lty = 2)
lines(c(0, 1100), c(50.35198, 1100 * 0.65 + 50.35198), lty = 2)
dev.off()
